# Generated by Django 4.2.3 on 2023-07-23 22:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('linkPrecedence', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='secondary', max_length=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('linkedId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contactmanagement.contact')),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
